#spring.config.import=optional:configserver:http://localhost:8888
spring:
  application:
    name: activity-service
  config:
    import: optional:configserver:http://localhost:8888

#############################################################
#server:
#  port: 82
#
#spring:
#  application:
#    name: activity-service
#  data:
#    mongodb:
#      uri: mongodb://admin:secret@localhost:27017/fitnessactivity?authSource=admin
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    instance-id: activity-service:192.168.1.22:82
#    hostname: 192.168.1.22
#    non-secure-port: 82
#
#rabbitmq:
#  exchange:
#    queue:
#      name: activity.queue
#    name: fitness.exchange
#    routing:
#      key: activity.tracking