spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

#####################################
#server:
#  port: 80
#
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: user-service
#              uri: lb://USER-SERVICE
#              predicates:
#                - Path=/apiv1/users/**
#            - id: activity-service
#              uri: lb://ACTIVITY-SERVICE
#              predicates:
#                - Path=/apiv1/activities/**
#            - id: ai-service
#              uri: lb://AI-SERVICE
#              predicates:
#                - Path=/apiv1/recommendations/**
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
# #   #fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    instance-id: api-gateway:192.168.1.22:80
#    hostname: 192.168.1.22
#    non-secure-port: 80