spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:http://localhost:8888

############################################################
#server:
#  port: 83
#
#spring:
#  application:
#    name: ai-service
#  data:
#    mongodb:
#      uri: mongodb://admin:secret@localhost:27018/fitness-recommendation?authSource=admin
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#eureka:
# client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    instance-id: ai-service:192.168.1.22:83
#    hostname: 192.168.1.22
#    non-secure-port: 83
#
#rabbitmq:
#  exchange:
#    queue:
#      name: activity.queue
#    name: fitness.exchange
#    routing:
#      key: activity.tracking
#
#gemini:
#  api:
#    url: ${GEMINI_API_URL}
#    key: ${GEMINI_API_KEY}