server:
  port: 82

spring:
  data:
    mongodb:
      uri: mongodb://admin:secret@localhost:27017/fitnessactivity?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: activity-service:192.168.1.22:82
    hostname: 192.168.1.22
    non-secure-port: 82

rabbitmq:
  exchange:
    queue:
      name: activity.queue
    name: fitness.exchange
    routing:
      key: activity.tracking


#####################################################
#server.port=82
## connecting to mongo db as docker container database
#spring.data.mongodb.uri=mongodb://admin:secret@localhost:27017/fitnessactivity?authSource=admin
## eureka client
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#eureka.instance.instance-id=activity-service:192.168.1.22:82
#eureka.instance.hostname=192.168.1.22
#eureka.instance.non-secure-port=82
## rabbit mq parameters
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
## rabbit mq
#rabbitmq.exchange.queue.name=activity.queue
#rabbitmq.exchange.name=fitness.exchange
#rabbitmq.exchange.routing.key=activity.tracking


