server:
  port: 81

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: user-service:192.168.1.22:81
    hostname: 192.168.1.22
    non-secure-port: 81

####################################################################
#server.port=81
## connecting to postgres db
#spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_user_db
# change when run as a set of containers
#spring.datasource.username=admin
#spring.datasource.password=password
#spring.datasource.driver-class-name=org.postgresql.Driver
## this will locate eureka server
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#eureka.instance.instance-id=user-service:192.168.1.22:81
#eureka.instance.hostname=192.168.1.22
#eureka.instance.non-secure-port=81