services:

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbit-server-cnr
    hostname: rmq
    restart: always
    #    volumes:
    #      - ./docker/volumes/rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  mongo1:
    image: mongo:8.0
    #image: mongo
    container_name: mongo-db-cnr1
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./docker/volumes/mongo_data/:/data/db/
      - /etc/timezone:/etc/timezone:ro

#  mongo-express:
#      image: mongo-express
#      container_name: mongo-express-ui-cnr
#      restart: always
#      ports:
#        - '8081:8081'
#      environment:
#        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#        ME_CONFIG_MONGODB_ADMINPASSWORD: secret
#        ME_CONFIG_MONGODB_URL: mongodb://admin:secret@mongo:27017/
#        #      ME_CONFIG_MONGODB_SERVER: mongo
#        #      ME_CONFIG_MONGODB_URL: mongodb://admin:secret@mongo:27017/
#        #      mongodb://admin:secret@localhost:27017/?authSource=admin
#        ME_CONFIG_BASICAUTH: false
#      depends_on:
#        - 'mongo'